sudo: required

language: c

os:
  - linux

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  - $CC -v

script:
  - cd ref
  - make test/test_dilithium3 CC=$CC CFLAGS="-fPIC -fprofile-arcs -ftest-coverage -march=native -O0 -g"
  - ./test/test_dilithium3

after_success:
  - lcov -d . --capture --output-file coverage.info
  - coveralls-lcov coverage.info
